"""Render the PRD state as Markdown, with a traceability appendix quoting every cited source line."""


def _cite(ids: list[str]) -> str:
    return f" <sub>[{', '.join(ids)}]</sub>" if ids else ""


def render(state: dict) -> str:
    p, ev = state["prd"], state["evidence"]
    out = [f"# {p['title']}", "",
           f"_Generated by PRDForge from {len(state['sources'])} sources and {len(ev)} evidence lines. "
           f"Critique issues per pass: {state.get('issue_history')}. "
           f"Remaining issues: {len(state.get('issues', []))}._", "",
           "## 1. Problem", p["problem_statement"], "", "## 2. Goals and success metrics", "",
           "| Goal | Metric | Evidence |", "|---|---|---|"]
    out += [f"| {g['goal']} | {g['metric']} | {', '.join(g['evidence_ids'])} |" for g in p["goals"]]
    out += ["", "## 3. Non-goals", *[f"- {n}" for n in p["non_goals"]],
            "", "## 4. Personas", *[f"- {x}" for x in p["personas"]], "", "## 5. User stories"]
    for s in p["user_stories"]:
        out += ["", f"### {s['id']} ({s['priority']})",
                f"As a **{s['as_a']}**, I want **{s['i_want']}**, so that **{s['so_that']}**.{_cite(s['evidence_ids'])}",
                "", "Acceptance criteria:"]
        out += [f"{i}. **Given** {a['given']}, **when** {a['when']}, **then** {a['then']}."
                for i, a in enumerate(s["acceptance_criteria"], 1)]
    out += ["", "## 6. Constraints", "", "| Category | Constraint | Evidence |", "|---|---|---|"]
    out += [f"| {c['category']} | {c['constraint']} | {', '.join(c['evidence_ids'])} |" for c in p["constraints"]]
    conflicts = {c["id"]: c for c in state.get("synthesis", {}).get("conflicts", [])}
    if p["decisions"]:
        out += ["", "## 7. Decisions"]
        for d in p["decisions"]:
            topic = conflicts.get(d["conflict_id"], {}).get("topic", "")
            out.append(f"- **{d['conflict_id']} {topic}:** {d['decision']} _Why:_ {d['rationale']}{_cite(d['evidence_ids'])}")
    out += ["", "## 8. Open questions"]
    for q in p["open_questions"]:
        tag = f"**{q['conflict_id']}** " if q["conflict_id"] else ""
        out.append(f"- {tag}{q['question']} _(owner: {q['owner']})_{_cite(q['evidence_ids'])}")
    out += ["", "## 9. Risks", *[f"- {r}" for r in p["risks"]]]
    if state.get("issues"):
        out += ["", "## Unresolved review issues", *[f"- {i}" for i in state["issues"]]]
    cited = sorted({e for sec in ("user_stories", "goals", "constraints", "decisions", "open_questions")
                    for it in p[sec] for e in it["evidence_ids"] if e in ev})
    out += ["", "---", "## Appendix: traceability", "", "| Id | Who | Said | Source |", "|---|---|---|---|"]
    out += [f"| {e} | {ev[e]['speaker']} | {ev[e]['text'].replace('|', '/')} | {ev[e]['source']} |" for e in cited]
    return "\n".join(out)
